import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type LanguageCode = 'EN' | 'ES' | 'ZH' | 'JA' | 'DE' | 'FR' | 'RU' | 'PT' | 'TR' | 'VI' | 'KO';

export interface Language {
  code: LanguageCode;
  name: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'EN', name: 'English', flag: '🇺🇸' },
  { code: 'ES', name: 'Español', flag: '🇪🇸' },
  { code: 'ZH', name: '中文', flag: '🇨🇳' },
  { code: 'JA', name: '日本語', flag: '🇯🇵' },
  { code: 'DE', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'FR', name: 'Français', flag: '🇫🇷' },
  { code: 'RU', name: 'Русский', flag: '🇷🇺' },
  { code: 'PT', name: 'Português', flag: '🇧🇷' },
  { code: 'TR', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'VI', name: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'KO', name: '한국어', flag: '🇰🇷' },
];

// High fidelity dictionary matching our professional web3 credit/reputation vocabulary
const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  EN: {
    'nav.home': 'Home',
    'nav.dashboard': 'My Karma',
    'nav.lenders': 'Sovereign Lenders',
    'nav.leaderboard': 'Global Rankings',
    'nav.aiReading': 'AI Reading',
    'nav.connect': 'Connect Wallet',
    'nav.disconnect': 'Disconnect',
    'nav.edit': 'Edit Profile',
    'nav.comingSoon': 'Soon',
    'hero.badge': '🔒 Credit Karma for Crypto Reputation · Sandbox Mode Enabled',
    'hero.titleLine1': 'Your Crypto',
    'hero.titleLine2': 'Reputation Score',
    'hero.subtitle': 'Like a credit score, but for Web3.',
    'hero.desc': 'Blockchain logs numbers, balances, and public addresses. Karma AI logs verified accountability. Measure trust, participation, reputation, and token conviction across crypto. Build your passport in seconds.',
    'solana.comingSoon': 'Token Coming Soon on Solana',
    'solana.utility': '$KARMA Utility Token',
    'solana.launch': 'SOLANA LAUNCH',
    'solana.powering': 'Powering zero-knowledge DeFi credit audits, instant reputation boosts, and cross-chain validator incentives. Hold $KARMA to claim multiplier passes on your credit scoring.',
    'landing.sliderHeader': 'Interactive Reputation Calculator',
    'landing.sliderDesc': 'Adjust the sliding quotient below to preview credit brackets, visual aura shifts, and governance multiplier weights.',
    'landing.reputationIndex': 'Reputation Quotient',
    'landing.activeAura': 'Active Aura Profile',
    'landing.unlockedBadges': 'Unlocked Badges',
    'landing.featuresHeader': 'The Pillars of Cryptographic Reputation',
    'landing.featuresDesc': 'Karma AI ingests smart contract activity history, token hold-intervals, and governance behavior blocks to compute the global trust index.',
    'landing.connectTitle': 'Forge Your Trust Passport',
    'landing.connectDesc': 'Securely connect your decentralized wallet index to synthesize metrics, earn non-custodial ratings, and unlock VIP liquidity routers.',
    'dashboard.certificateTitle': 'Reputation Certificate',
    'dashboard.reputationCert': 'Verified Sovereign Credit Record',
    'dashboard.streak': 'Holding Streak Title',
    'dashboard.ranking': 'Global Registry Rank',
    'dashboard.scoreBreakdown': 'Reputation Score Breakdown',
    'dashboard.identityPillars': 'Behavior Identity Pillars',
    'dashboard.liveAnalytics': 'Live Sandbox Analytics',
    'dashboard.recentActivity': 'Recent Activity Log',
    'dashboard.activeState': 'Sovereign Node Identity Active',
    'lenders.title': 'Sovereign Lenders',
    'lenders.subtitle': 'Instant Liquidity Router',
    'lenders.desc': 'Pre-qualify and anchor direct non-collateralized loan proposals instantly. Higher Reputation scores dynamically unlock competitive APR reductions and massive borrow limits.',
    'lenders.dynamicLimit': 'Dynamic Lend Limit',
    'lenders.scoreBarrier': 'Required Quotient Rating',
    'lenders.apr': 'Representative APR',
    'lenders.approvalRate': 'Underwriting Confidence',
    'lenders.requestQuote': 'Execute Liquidity Handshake',
    'leaderboard.title': 'Global Wallet Arena',
    'leaderboard.subtitle': 'On-chain High Score Registry',
    'leaderboard.desc': 'Reputation rankings updated dynamically. Verify on-chain hold records, governance streaks, and elite credit status across the registry.',
    'leaderboard.score': 'Score',
    'leaderboard.streakBadge': 'Streak',
    'leaderboard.search': 'Filter nodes by wallet address...',
    'ai.title': 'AI Karma Oracle',
    'ai.subtitle': 'Calibrating Neural Sentiment Aura...',
    'ai.desc': 'Our neural reputation scoring model will audit your public state block records, wallet age metrics, and contract history signature to generate custom written insights.',
    'ai.requestAudit': 'Request Deep AI Karma Audit',
    'ai.analyzing': 'Analyzing Transaction Underlays...',
    'footer.brand': 'Credit Karma for Crypto Reputation. Merging machine learning underlays, predictive FICO-style scoring algorithms, and zero-knowledge identity anchors.',
    'footer.infrastructure': 'Infrastructure',
    'footer.ecosystem': 'Ecosystem',
    'footer.socialVectors': 'Social Vectors'
  },
  ES: {
    'nav.home': 'Inicio',
    'nav.dashboard': 'Mi Karma',
    'nav.lenders': 'Prestamistas Soberanos',
    'nav.leaderboard': 'Clasificaciones',
    'nav.aiReading': 'Lectura de IA',
    'nav.connect': 'Conectar Cartera',
    'nav.disconnect': 'Desconectar',
    'nav.edit': 'Editar Perfil',
    'nav.comingSoon': 'Pronto',
    'hero.badge': '🔒 Credit Karma para reputación criptográfica · Modo Sandbox Activo',
    'hero.titleLine1': 'Tu Puntuación de',
    'hero.titleLine2': 'Reputación Cripto',
    'hero.subtitle': 'Como un historial crediticio, pero para Web3.',
    'hero.desc': 'La cadena de bloques registra números, saldos y direcciones públicas. Karma AI registra la responsabilidad verificada. Mide la confianza, participación, reputación y convicción de tokens. Crea tu pasaporte en segundos.',
    'solana.comingSoon': 'Token muy pronto en Solana',
    'solana.utility': 'Token de Utilidad $KARMA',
    'solana.launch': 'LANZAMIENTO SOLANA',
    'solana.powering': 'Impulsando auditorías de crédito DeFi de conocimiento cero, aumentos instantáneos de reputación e incentivos de validadores entre cadenas. Mantén $KARMA para reclamar pases multiplicadores de su puntuación.',
    'landing.sliderHeader': 'Calculadora Interactiva de Reputación',
    'landing.sliderDesc': 'Ajusta el cociente deslizante a continuación para previsualizar límites de crédito, cambios de aura visual y pesos de multiplicador de gobernanza.',
    'landing.reputationIndex': 'Cociente de Reputación',
    'landing.activeAura': 'Perfil de Aura Activo',
    'landing.unlockedBadges': 'Insignias Desbloqueadas',
    'landing.featuresHeader': 'Los Pilares de la Reputación Criptográfica',
    'landing.featuresDesc': 'Karma AI procesa el historial de contratos inteligentes, intervalos de retención de tokens y bloques de comportamiento de gobernanza para computar el índice de confianza global.',
    'landing.connectTitle': 'Forja Tu Pasaporte de Confianza',
    'landing.connectDesc': 'Conecta de forma segura el índice de tu cartera descentralizada para sintetizar métricas, obtener calificaciones sin custodia y desbloquear enrutadores de liquidez VIP.',
    'dashboard.certificateTitle': 'Certificado de Reputación',
    'dashboard.reputationCert': 'Historial de Crédito Soberano Verificado',
    'dashboard.streak': 'Título de racha de retención',
    'dashboard.ranking': 'Rango del Registro Global',
    'dashboard.scoreBreakdown': 'Desglose de Puntuación de Reputación',
    'dashboard.identityPillars': 'Pilares de Identidad Conductual',
    'dashboard.liveAnalytics': 'Análisis del Sandbox en Vivo',
    'dashboard.recentActivity': 'Registro de Actividad Reciente',
    'dashboard.activeState': 'Identidad de Nodo Soberano Activa',
    'lenders.title': 'Prestamistas Soberanos',
    'lenders.subtitle': 'Enrutador de Liquidez Instantánea',
    'lenders.desc': 'Precalifica y asegura propuestas de préstamos directos sin colateral al instante. Las puntuaciones de reputación más altas desbloquean de forma dinámica reducciones competitivas de APR y límites de préstamo masivos.',
    'lenders.dynamicLimit': 'Límite Dinámico Préstamo',
    'lenders.scoreBarrier': 'Calificación de Cociente Requerida',
    'lenders.apr': 'Tasa Interés Típica',
    'lenders.approvalRate': 'Confianza de Suscripción',
    'lenders.requestQuote': 'Ejecutar Acuerdo de Liquidez',
    'leaderboard.title': 'Arena Global de Carteras',
    'leaderboard.subtitle': 'Registro de Puntuación Alta',
    'leaderboard.desc': 'Clasificaciones de reputación actualizadas dinámicamente. Verifica registros de tenencia, rachas de gobernanza y estatus de crédito de élite.',
    'leaderboard.score': 'Puntos',
    'leaderboard.streakBadge': 'Racha',
    'leaderboard.search': 'Filtrar nodos por dirección...',
    'ai.title': 'Oráculo de Karma IA',
    'ai.subtitle': 'Calibrando el Aura de Sentimiento Neuronal...',
    'ai.desc': 'Nuestro modelo de puntuación de reputación neuronal auditará tus registros de bloques públicos, métricas de edad de cartera y firmas de contratos para generar análisis personalizados por escrito.',
    'ai.requestAudit': 'Solicitar Auditoría IA Profunda',
    'ai.analyzing': 'Analizando Capas de Transacción...',
    'footer.brand': 'Credit Karma para reputación en Web3. Uniendo capas de aprendizaje automático, algoritmos predictivos de puntuación y anclas de identidad de conocimiento cero.',
    'footer.infrastructure': 'Infraestructura',
    'footer.ecosystem': 'Ecosistema',
    'footer.socialVectors': 'Vectores Sociales'
  },
  ZH: {
    'nav.home': '主页',
    'nav.dashboard': '我的信用',
    'nav.lenders': '主权借贷',
    'nav.leaderboard': '全球排行',
    'nav.aiReading': 'AI 评估',
    'nav.connect': '连接钱包',
    'nav.disconnect': '断开连接',
    'nav.edit': '编辑资料',
    'nav.comingSoon': '即将推出',
    'hero.badge': '🔒 加密信誉链上信用评级 · 模拟沙盒模式已启用',
    'hero.titleLine1': '您的加密',
    'hero.titleLine2': '名誉与信用评分',
    'hero.subtitle': 'Web3 时代的信用分数系统。',
    'hero.desc': '区块链只记录余额和公开地址。Karma AI 则记录经核实的数字信用。它通过智能算法量化信任度、治理参与、持有信仰。几秒内合成您的去中心化信用通行证。',
    'solana.comingSoon': 'Solana 平台代币发售在即',
    'solana.utility': '$KARMA 实用通证',
    'solana.launch': 'SOLANA 首发',
    'solana.powering': '驱动零知识证明 DeFi 信用审计、即时信誉提升、以及跨链验证人激励。持有 $KARMA 即可享受信用评分加成倍数。',
    'landing.sliderHeader': '交互式信誉评分预测器',
    'landing.sliderDesc': '随意调整下方的信誉滑块，预览对应的信用区间、视觉光环转变、以及治理投票权乘数。',
    'landing.reputationIndex': '信誉系数',
    'landing.activeAura': '当前光环形象',
    'landing.unlockedBadges': '已解勋章',
    'landing.featuresHeader': '加密世界信誉的支柱维度',
    'landing.featuresDesc': 'Karma AI 全方位解析您的智能合约交互历史、代币持有周期、以及治理行为块来科学运算全局信任指数。',
    'landing.connectTitle': '铸造您的去中心化信誉护照',
    'landing.connectDesc': '安全地连接您的数字钱包，实时扫描多维指标，收获高信誉无托管评级，解锁专属流动性路由器。',
    'dashboard.certificateTitle': '信誉荣誉证书',
    'dashboard.reputationCert': '经验证的主权信贷档案',
    'dashboard.streak': '链上持有天数',
    'dashboard.ranking': '全球注册排名',
    'dashboard.scoreBreakdown': '信誉指数多维剖析',
    'dashboard.identityPillars': '行为身份指标支柱',
    'dashboard.liveAnalytics': '实时链上行为沙盒分析',
    'dashboard.recentActivity': '近期链上活动日志',
    'dashboard.activeState': '主权节点身份已保活',
    'lenders.title': '链上主权借贷',
    'lenders.subtitle': '即时借贷匹配路由器',
    'lenders.desc': '无需抵押直接发起贷款资格预审。名誉积分越出众，动态享有的利息折扣就越高，借款授信额度也越可观。',
    'lenders.dynamicLimit': '可融信贷额度',
    'lenders.scoreBarrier': '准入名誉门槛',
    'lenders.apr': '基准参考利率',
    'lenders.approvalRate': '授信核验置信度',
    'lenders.requestQuote': '执行签名放款握手',
    'leaderboard.title': '全球钱包竞技场',
    'leaderboard.subtitle': '链上名誉排行榜单',
    'leaderboard.desc': '动态刷新的实名信誉档案。在此公开验证链上持有分布、治理连击、以及精英信用等级。',
    'leaderboard.score': '信誉分数',
    'leaderboard.streakBadge': '连击',
    'leaderboard.search': '输入钱包地址检索节点...',
    'ai.title': 'AI 信誉预言机',
    'ai.subtitle': '神经网络信誉光环标定中...',
    'ai.desc': 'AI 模型支持深度剖析钱包交易链、区块链时长、与合约行为记录，为您全自动生成专属的高维度信用评估分析。',
    'ai.requestAudit': '一键发起 AI 深度信誉审计',
    'ai.analyzing': '分析交易底层网络中...',
    'footer.brand': '面向 Web3 的链上信用评分及信誉协议。融合机器学习下层系统、FICO 式预测模型、与零知识锚定器。',
    'footer.infrastructure': '基础设施',
    'footer.ecosystem': '生态系统',
    'footer.socialVectors': '社区渠道'
  },
  JA: {
    'nav.home': 'ホーム',
    'nav.dashboard': 'マイカルマ',
    'nav.lenders': '暗号レンディング',
    'nav.leaderboard': 'リーダーボード',
    'nav.aiReading': 'AI 診断',
    'nav.connect': 'ウォレット接続',
    'nav.disconnect': '接続解除',
    'nav.edit': 'プロフィール編集',
    'nav.comingSoon': '近日登場',
    'hero.badge': '🔒 暗号レピュテーション의 格付け · 샌드박스 모드 활성화됨',
    'hero.titleLine1': 'Web3の世界で',
    'hero.titleLine2': '信用を可視化する',
    'hero.subtitle': 'クレジットスコア。ただし、DeFi向け。',
    'hero.desc': 'ブロックチェーンは残高と公開アドレスのみを記録します。Karma AIは検証済みの信頼行動を客観評価。トークンの保有期間やガバナンスへの貢献度から、数秒で信頼パスポートを合成。',
    'solana.comingSoon': 'Solana プラットフォームにてトークンまもなく公開',
    'solana.utility': '$KARMA 実用トークン',
    'solana.launch': 'SOLANA ローンチ',
    'solana.powering': 'ゼロ知識 DeFiスコア監査、即時レピュテーション向上、およびクロスチェーンバリデーター報酬のインセンティブ設計。トークン保有者は評価の増加乗数を受け取ります。',
    'landing.sliderHeader': 'レピュテーション構築シミュレーター',
    'landing.sliderDesc': 'スライダーを動かして、信用枠、オーラの変化、意思決定マルチプライヤーの変化を体感してください。',
    'landing.reputationIndex': 'レピュテーション指数',
    'landing.activeAura': 'アクティブオーラ',
    'landing.unlockedBadges': 'アンロックした記章',
    'landing.featuresHeader': '暗号資産信頼の多層ピラー',
    'landing.featuresDesc': 'Karma AI は独自アルゴリズムを活用し、スマートコントラクトの実行履歴、HODL日数、ガバナンスへの参加から総合実積をスコア化します。',
    'landing.connectTitle': '信頼のパスポートを鋳造する',
    'landing.connectDesc': '分散型ウォレットを安全に連携。マルチチェーンの実積指標を監査し、特別なレンディングルーターを解禁してください。',
    'dashboard.certificateTitle': 'レピュテーション証明書',
    'dashboard.reputationCert': '検証済みの自律的信用アーカイブ',
    'dashboard.streak': 'トークン保有日数',
    'dashboard.ranking': 'グローバル順位',
    'dashboard.scoreBreakdown': 'レピュテーションの内訳分析',
    'dashboard.identityPillars': '行動パターンの基盤ピラー',
    'dashboard.liveAnalytics': 'リアルタイム・チェーン分析',
    'dashboard.recentActivity': '直近のスマートトランザクション',
    'dashboard.activeState': 'ノード信頼アイデンティティ稼働中',
    'lenders.title': '金融レンディングルーター',
    'lenders.subtitle': '無担保融資エンジン',
    'lenders.desc': '事前審査と融資提案。レピュテーションスコアが高いほど優遇された低金利(APR)割引と巨額の借入限度枠が割り当てられます。',
    'lenders.dynamicLimit': '最大レンディング利用限度',
    'lenders.scoreBarrier': '必要レピュテーション',
    'lenders.apr': '標準貸出金利',
    'lenders.approvalRate': '審査合格確度',
    'lenders.requestQuote': '信用契約の署名・実行',
    'leaderboard.title': 'ウォレット対抗アリーナ',
    'leaderboard.subtitle': '信頼性のスコアボード',
    'leaderboard.desc': '毎分最新。オンチェーンで真に評価のお墨付きを得た投資ストリーク、投票、上位ウォレットを表示。',
    'leaderboard.score': 'スコア',
    'leaderboard.streakBadge': 'ストリーク',
    'leaderboard.search': 'ウォレットアドレスでノードを検索...',
    'ai.title': 'AI カルマオラクル',
    'ai.subtitle': '神経解釈オーラキャリブレーション...',
    'ai.desc': 'AIを用いて過去の取引傾向、アドレス年齢、投票履歴を多面的に学習、自動でパーソナライズされた深い評価書を作成。',
    'ai.requestAudit': 'AI 深層評価監査を実行する',
    'ai.analyzing': '取引レイヤーをスキャン中...',
    'footer.brand': '分散型ウェブにおける暗号資産の信頼。独自の機械学習エンジンと、ゼロ知識のトラストアイデンティティシステム。',
    'footer.infrastructure': 'インフラストラクチャー',
    'footer.ecosystem': 'エコシステム',
    'footer.socialVectors': 'ソーシャルチャンネル'
  },
  DE: {
    'nav.home': 'Start',
    'nav.dashboard': 'Mein Karma',
    'nav.lenders': 'Souveräne Kreditgeber',
    'nav.leaderboard': 'Globale Rangliste',
    'nav.aiReading': 'KI-Analyse',
    'nav.connect': 'Wallet verbinden',
    'nav.disconnect': 'Trennen',
    'nav.edit': 'Profil bearbeiten',
    'nav.comingSoon': 'Bald',
    'hero.badge': '🔒 Krypto-Kredit-Karma für verifizierten Ruf · Sandbox-Modus Aktiv',
    'hero.titleLine1': 'Dein Krypto',
    'hero.titleLine2': 'Reputations-Score',
    'hero.subtitle': 'Wie ein FICO-Score, aber für Web3.',
    'hero.desc': 'Die Blockchain speichert nur Salden und öffentliche Adressen. Karma AI misst verifizierte Zuverlässigkeit, Governance-Beteiligung, HODL-Gewohnheiten und Krypto-Engagement. Erstelle deinen Ausweis in Sekunden.',
    'solana.comingSoon': 'Token demnächst auf Solana',
    'solana.utility': '$KARMA Utility-Token',
    'solana.launch': 'SOLANA LAUNCH',
    'solana.powering': 'Unterstützt wissensfreie DeFi-Kreditprüfungen, sofortige Erhöhung des Rufs und anreizbasierte kettenübergreifende Validierung. Halte $KARMA für Multiplikator-Pässe.',
    'landing.sliderHeader': 'Interaktiver Reputationsrechner',
    'landing.sliderDesc': 'Passe den Reputations-Quotienten an, um Kreditobergrenzen, visuelle Aura-Änderungen und Governance-Multiplikatoren zu sehen.',
    'landing.reputationIndex': 'Reputations-Quotient',
    'landing.activeAura': 'Aktive Aura',
    'landing.unlockedBadges': 'Freigeschaltete Abzeichen',
    'landing.featuresHeader': 'Die Säulen Krypto-Souveräner Reputation',
    'landing.featuresDesc': 'Karma AI analysiert Smart-Contract-Interaktionen, Token-Haltedauer und Governance-Stimmen, um das Vertrauensniveau präzise zu ermitteln.',
    'landing.connectTitle': 'Erstelle deinen Vertrauensausweis',
    'landing.connectDesc': 'Verbinde deine Wallet, analysiere deine Krypto-Kennzahlen und schalte VIP-Liquiditätsrouten ohne Depotverwahrung frei.',
    'dashboard.certificateTitle': 'Reputationszertifikat',
    'dashboard.reputationCert': 'Verifizierter Souveräner Kreditauszug',
    'dashboard.streak': 'HODL-Strähne',
    'dashboard.ranking': 'Globaler Registerrang',
    'dashboard.scoreBreakdown': 'Aufschlüsselung der Reputation',
    'dashboard.identityPillars': 'Verhaltensidentitäts-Säulen',
    'dashboard.liveAnalytics': 'Live Sandbox Analytics',
    'dashboard.recentActivity': 'Aktuelles Aktivitätsprotokoll',
    'dashboard.activeState': 'Souveräne Node-Identität Aktiv',
    'lenders.title': 'Souveräne Kreditgeber',
    'lenders.subtitle': 'Instant-Liquiditätsrouter',
    'lenders.desc': 'Qualifiziere dich ohne Sicherheiten für Kredite. Höhere Reputations-Scores schalten günstigere Zinssätze (APR) und erhebliche Kreditsummen frei.',
    'lenders.dynamicLimit': 'Dynamisches Kreditlimit',
    'lenders.scoreBarrier': 'Erforderliches Quotient-Rating',
    'lenders.apr': 'Repräsentativer effektiver Jahreszins',
    'lenders.approvalRate': 'Zeichnungskonfidenz',
    'lenders.requestQuote': 'Finanzierungshandshake signieren',
    'leaderboard.title': 'Globale Wallet-Arena',
    'leaderboard.subtitle': 'Das Reputations-Highscore-Register',
    'leaderboard.desc': 'Echtzeit-Aktualisierung. Verifiziere HODL-Zyklen, Abstimmungsverhalten und exklusiven Kreditstatus.',
    'leaderboard.score': 'Punkte',
    'leaderboard.streakBadge': 'Strähne',
    'leaderboard.search': 'Suchen nach Wallet-Adresse...',
    'ai.title': 'KI-Karma-Orakel',
    'ai.subtitle': 'Neuronale Aura-Kalibrierung läuft...',
    'ai.desc': 'Unser neuronales System analysiert Wallet-Verhalten, Blockspanne und Smart-Contract-Interaktionen für deine persönliche reputative Krypto-Bewertung.',
    'ai.requestAudit': 'Tiefenanalyse starten',
    'ai.analyzing': 'Transaktionsebenen scannen...',
    'footer.brand': 'Credit Karma für Web3-Reputation. Verknüpft Machine Learning, prädiktive Scoring-Algorithmen und wissensfreie Identitäts-Anker auf DeFi-Blockchains.',
    'footer.infrastructure': 'Infrastruktur',
    'footer.ecosystem': 'Ökosystem',
    'footer.socialVectors': 'Soziale Kanäle'
  },
  FR: {
    'nav.home': 'Accueil',
    'nav.dashboard': 'Mon Karma',
    'nav.lenders': 'Prêteurs Souverains',
    'nav.leaderboard': 'Classement',
    'nav.aiReading': 'Rapport IA',
    'nav.connect': 'Se Connecter',
    'nav.disconnect': 'Déconnexion',
    'nav.edit': 'Modifier Profil',
    'nav.comingSoon': 'Bientôt',
    'hero.badge': '🔒 Crédit-Karma pour Réputation Crypto · Mode Sandbox Activé',
    'hero.titleLine1': 'Votre Réputation',
    'hero.titleLine2': 'Et Score Crypto',
    'hero.subtitle': 'Un score de confiance, pensé pour la DeFi.',
    'hero.desc': 'La blockchain enregistre des soldes et des transactions. Karma AI analyse la responsabilité numérique. Évaluez la confiance, la gouvernance et l\'engagement en quelques secondes via un passeport souverain.',
    'solana.comingSoon': 'Jeton bientôt disponible sur Solana',
    'solana.utility': 'Jeton d\'Utilité $KARMA',
    'solana.launch': 'LANCEMENT SOLANA',
    'solana.powering': 'Alimente des audits de crédit DeFi confidentiels, des améliorations instantanées de score et des incitations. Détenez $KARMA pour réclamer vos multiplicateurs.',
    'landing.sliderHeader': 'Simulateur Interactif de Reputation',
    'landing.sliderDesc': 'Ajustez le quotient pour simuler vos paliers de crédit, variations d\'aura, et coefficients de gouvernance.',
    'landing.reputationIndex': 'Quotient de Réputation',
    'landing.activeAura': 'Aura Active',
    'landing.unlockedBadges': 'Badges Déverrouillés',
    'landing.featuresHeader': 'Les Piliers du Score de Confiance Crypto',
    'landing.featuresDesc': 'Karma AI consolide l\'historique d\'interaction de contrats intelligents, l\'ancienneté de hold, et la gouvernance active.',
    'landing.connectTitle': 'Forgez Votre Passeport Trust',
    'landing.connectDesc': 'Connectez votre portefeuille décentralisé pour compiler vos performances et déverrouiller des taux privilégiés VIP de liquidité.',
    'dashboard.certificateTitle': 'Certificat de Réputation',
    'dashboard.reputationCert': 'Dossier de Crédit Souverain Vérifié',
    'dashboard.streak': 'Série de Hold',
    'dashboard.ranking': 'Rang du Registre Global',
    'dashboard.scoreBreakdown': 'Détail de votre Indice de Confiance',
    'dashboard.identityPillars': 'Piliers d\'Identité Comportementale',
    'dashboard.liveAnalytics': 'Analyses en Direct de la Sandbox',
    'dashboard.recentActivity': 'Flux d\'Activités Récentes',
    'dashboard.activeState': 'Identité du Nœud Souverain Active',
    'lenders.title': 'Prêteurs Souverains',
    'lenders.subtitle': 'Routeur de Liquidité Instantanée',
    'lenders.desc': 'Bénéficiez instantanément de propositions de financement non-collatéralisé. Un meilleur score déverrouille de manière dynamique des réductions d\'APR massives.',
    'lenders.dynamicLimit': 'Limite de Financement',
    'lenders.scoreBarrier': 'Quotient de Confiance Requis',
    'lenders.apr': 'Taux d\'Intérêt Annuel (APR)',
    'lenders.approvalRate': 'Niveau de Crédibilité',
    'lenders.requestQuote': 'Signer l\'Accord Financier',
    'leaderboard.title': 'Arène Globale des Portefeuilles',
    'leaderboard.subtitle': 'Registre du Score Board Réputation',
    'leaderboard.desc': 'Mise à jour en temps réel. Vérifiez l\'engagement on-chain, les cycles de hold, et le statut légitime de crédit.',
    'leaderboard.score': 'Karma Score',
    'leaderboard.streakBadge': 'Série',
    'leaderboard.search': 'Rechercher un portefeuille dans le registre...',
    'ai.title': 'Oracle de Karma IA',
    'ai.subtitle': 'Calibration Neurone de l\'Aura de Réputation...',
    'ai.desc': 'Notre modèle intelligent audite vos activités de blocs publics, l\'âge du portefeuille et vos interactions pour rédiger un rapport approfondi personnalisé.',
    'ai.requestAudit': 'Lancer un Rapport AI Approfondi',
    'ai.analyzing': 'Analyse des blocs de transactions...',
    'footer.brand': 'Crédit Karma pour la confiance souveraine sur Web3. Fusionne l\'apprentissage automatique, les algorithmes prédictifs et les mécanismes de confidentialité.',
    'footer.infrastructure': 'Infrastructure',
    'footer.ecosystem': 'Écosystème',
    'footer.socialVectors': 'Canaux Sociaux'
  },
  RU: {
    'nav.home': 'Главная',
    'nav.dashboard': 'Мой Карма',
    'nav.lenders': 'Суверенные Кредиторы',
    'nav.leaderboard': 'Рейтинг',
    'nav.aiReading': 'ИИ Диагностика',
    'nav.connect': 'Подключить Кошелек',
    'nav.disconnect': 'Отключить',
    'nav.edit': 'Редактировать',
    'nav.comingSoon': 'Скоро',
    'hero.badge': '🔒 Кредитная Карма за Крипто-Репутацию · Режим песочницы включен',
    'hero.titleLine1': 'Ваша Kрипто',
    'hero.titleLine2': 'Репутация и Счёт',
    'hero.subtitle': 'Как кредитный скоринг, только для Web3.',
    'hero.desc': 'Блокчейн хранит балансы и транзакции. Karma AI оценивает верифицированное доверие. Измеряйте активность, репутацию и преданность токенам во всей крипте. Создайте паспорт за пару секунд.',
    'solana.comingSoon': 'Запуск токена скоро на Solana',
    'solana.utility': 'Утилитарный Токен $KARMA',
    'solana.launch': 'ЗАПУСК НА SOLANA',
    'solana.powering': 'Обеспечение конфиденциальных DeFi кредитных аудитов с нулевым разглашением, мгновенное повышение репутации и награды кросс-чейн валидаторов. Держите $KARMA для получения мультипликаторов.',
    'landing.sliderHeader': 'Интерактивный Калькулятор Репутации',
    'landing.sliderDesc': 'Изменяйте ползунок репутации ниже, чтобы увидеть лимиты кредитования, изменения ауры и силу голоса.',
    'landing.reputationIndex': 'Индекс Репутации',
    'landing.activeAura': 'Активный Профиль Ауры',
    'landing.unlockedBadges': 'Полученные Значки',
    'landing.featuresHeader': 'Столпы Криптографической Репутации',
    'landing.featuresDesc': 'Karma AI анализирует активность смарт-контрактов, сроки удержания токенов и историю голосования для расчета глобального доверия.',
    'landing.connectTitle': 'Создайте Свой Паспорт Доверия',
    'landing.connectDesc': 'Безопасно подключите ваш децентрализованный кошелек для анализа показателей, получения высоких рейтингов без доверительного управления.',
    'dashboard.certificateTitle': 'Сертификат Репутации',
    'dashboard.reputationCert': 'Подтвержденная Кредитная История',
    'dashboard.streak': 'Серия Удержания Токенов',
    'dashboard.ranking': 'Глобальное Место в Реестре',
    'dashboard.scoreBreakdown': 'Детализация Показателя Репутации',
    'dashboard.identityPillars': 'Показатели Поведенческой Идентичности',
    'dashboard.liveAnalytics': 'Живая Аналитика Песочницы',
    'dashboard.recentActivity': 'Журнал Последней Активности',
    'dashboard.activeState': 'Активный Суверенный Нод',
    'lenders.title': 'Суверенные Кредиторы',
    'lenders.subtitle': 'Маршрутизатор Мгновенной Ликвидности',
    'lenders.desc': 'Мгновенно получайте предложения по беззалоговым кредитам. Высокие оценки репутации снижают процентные ставки (APR) и увеличивают кредитные лимиты.',
    'lenders.dynamicLimit': 'Лимит Кредитования',
    'lenders.scoreBarrier': 'Требуемый Рейтинг Коэффициента',
    'lenders.apr': 'Годовая Процентная Ставка (APR)',
    'lenders.approvalRate': 'Уровень Доверия Модели скоринга',
    'lenders.requestQuote': 'Подписать Кредитную Сделку',
    'leaderboard.title': 'Глобальная Арена Кошельков',
    'leaderboard.subtitle': 'Реестр Высоких Репутаций',
    'leaderboard.desc': 'Рейтинги обновляются в реальном времени. Проверяйте показатели держателей токенов, стрики участия в ДАО и элитных членов.',
    'leaderboard.score': 'Баллы',
    'leaderboard.streakBadge': 'Стрик',
    'leaderboard.search': 'Поиск адреса в реестре...',
    'ai.title': 'ИИ Оракул Karma',
    'ai.subtitle': 'Калибровка Ауры Нейросетевого Анализа...',
    'ai.desc': 'Наш ИИ-оракул анализирует публичные транзакции, возраст адреса и взаимодействие с протоколами для создания детального аналитического отчета.',
    'ai.requestAudit': 'Запросить Глубокий ИИ-Аудит',
    'ai.analyzing': 'Анализ транзакционного графа...',
    'footer.brand': 'Кредитная Карма для репутации в Web3. Объединяет нейросети, скоринг-алгоритмы и децентрализованные идентификаторы.',
    'footer.infrastructure': 'Инфраструктура',
    'footer.ecosystem': 'Экосистема',
    'footer.socialVectors': 'Социальные Сети'
  },
  PT: {
    'nav.home': 'Início',
    'nav.dashboard': 'Meu Karma',
    'nav.lenders': 'Credores Soberanos',
    'nav.leaderboard': 'Classificação',
    'nav.aiReading': 'Leitura de IA',
    'nav.connect': 'Conectar Carteira',
    'nav.disconnect': 'Desconectar',
    'nav.edit': 'Editar Perfil',
    'nav.comingSoon': 'Em breve',
    'hero.badge': '🔒 Crédito Karma para reputação cripto · Modo Sandbox ativo',
    'hero.titleLine1': 'Seu Score de',
    'hero.titleLine2': 'Reputação Cripto',
    'hero.subtitle': 'Tipo um Serasa Score, mas para a Web3.',
    'hero.desc': 'A blockchain registra números, saldos e endereços públicos. A Karma AI analisa responsabilidade verificada. Meça confiança, governança, hold e convicção de tokens. Crie seu passaporte em segundos.',
    'solana.comingSoon': 'Token em breve na Solana',
    'solana.utility': 'Token de Utilidade $KARMA',
    'solana.launch': 'LANÇAMENTO SOLANA',
    'solana.powering': 'Viabilizando auditorias de crédito DeFi confidenciais, aumentos instantâneos de reputação e incentivos para validadores. Segure $KARMA para garantir seus multiplicadores de score.',
    'landing.sliderHeader': 'Calculadora de Reputação Interativa',
    'landing.sliderDesc': 'Ajuste o controle deslizante abaixo para simular limites de crédito, mudanças de aura visual e multiplicadores de governança.',
    'landing.reputationIndex': 'Índice de Reputação',
    'landing.activeAura': 'Aura Ativa',
    'landing.unlockedBadges': 'Conquistas Desbloqueadas',
    'landing.featuresHeader': 'Os Pilares da Reputação Cripto',
    'landing.featuresDesc': 'A Karma AI analisa o histórico de contratos inteligentes, períodos de hold de tokens e comportamento de governança para calcular sua reputação global.',
    'landing.connectTitle': 'Crie seu Passaporte de Confiança',
    'landing.connectDesc': 'Conecte sua carteira de forma segura para sintetizar dados, ganhar classificações não-custodiais e obter vantagens exclusivas.',
    'dashboard.certificateTitle': 'Certificado de Reputação',
    'dashboard.reputationCert': 'Histórico de Crédito Soberano Verificado',
    'dashboard.streak': 'Dias Seguidos de Seguro de Tokens',
    'dashboard.ranking': 'Classificação Global',
    'dashboard.scoreBreakdown': 'Detalhamento do Score de Reputação',
    'dashboard.identityPillars': 'Pilares de Identidade Comportamental',
    'dashboard.liveAnalytics': 'Análises de Rede ao Vivo',
    'dashboard.recentActivity': 'Histórico de Atividade Recente',
    'dashboard.activeState': 'Nó de Identidade Ativo',
    'lenders.title': 'Credores Soberanos',
    'lenders.subtitle': 'Roteador de Liquidez Sem Garantia',
    'lenders.desc': 'Pré-qualifique e garanta empréstimos sem colateral instantaneamente. Scores mais altos desbloqueiam taxas de juros (APR) melhores e maiores limites.',
    'lenders.dynamicLimit': 'Limite de Financiamento',
    'lenders.scoreBarrier': 'Score Mínimo Exigido',
    'lenders.apr': 'Taxa de Juros de Referência (APR)',
    'lenders.approvalRate': 'Nível de Confiança de Crédito',
    'lenders.requestQuote': 'Assinar Contrato de Liquidez',
    'leaderboard.title': 'Arena Global de Carteiras',
    'leaderboard.subtitle': 'Quadro de Líderes de Reputação',
    'leaderboard.desc': 'Atualizado em tempo real. Verifique histórico de holders, participação ativa em DAOs e os carteiras de nível de elite.',
    'leaderboard.score': 'Score',
    'leaderboard.streakBadge': 'Série',
    'leaderboard.search': 'Buscar carteira no registro...',
    'ai.title': 'Oráculo de Karma IA',
    'ai.subtitle': 'Ajustando a Aura Espiritual de IA...',
    'ai.desc': 'Nosso modelo de IA analisa de forma inteligente o histórico de blocos, contratos e idade da carteira para redigir uma avaliação personalizada descritiva.',
    'ai.requestAudit': 'Solicitar Auditoria Profunda de IA',
    'ai.analyzing': 'Analisando transações on-chain...',
    'footer.brand': 'Crédito Karma para reputação Web3. Unindo aprendizado de máquina, algoritmos preditivos e privacidade confidencial sólida.',
    'footer.infrastructure': 'Infraestrutura',
    'footer.ecosystem': 'Ecossistema',
    'footer.socialVectors': 'Redes Sociais'
  },
  TR: {
    'nav.home': 'Ana Sayfa',
    'nav.dashboard': 'Karman',
    'nav.lenders': 'Egemen Borç Verenler',
    'nav.leaderboard': 'Küresel Sıralama',
    'nav.aiReading': 'Yapay Zeka Analizi',
    'nav.connect': 'Cüzdanı Bağla',
    'nav.disconnect': 'Bağlantıyı Kes',
    'nav.edit': 'Profili Düzenle',
    'nav.comingSoon': 'Yakında',
    'hero.badge': '🔒 Kripto İtibarı için Kredi Karması · Sandbox Modu Etkin',
    'hero.titleLine1': 'Kripto İtibar',
    'hero.titleLine2': 've Kredi Skorunuz',
    'hero.subtitle': 'Web3 dünyası için kredi notunuz.',
    'hero.desc': 'Blokzincir bakiyeleri ve adresleri kaydeder; Karma AI ise doğrulanmış güvenli davranışı değerlendirir. Kriptoda aktif katılımı, itibarı ve hold kararlılığını ölçün. Saniyeler içinde itibar pasaportunuzu oluşturun.',
    'solana.comingSoon': 'Token yakında Solana ağında',
    'solana.utility': '$KARMA Yardımcı Tokenı',
    'solana.launch': 'SOLANA LANSMANI',
    'solana.powering': 'Sıfır bilgi korumalı DeFi kredi denetimleri, anında itibar artışı ve cross-chain doğrulayıcı ödülleri sağlar. Skor çarpanı kazanmak için $KARMA tutun.',
    'landing.sliderHeader': 'İnteraktif İtibar Hesaplayıcı',
    'landing.sliderDesc': 'Kredi limitlerini, görsel aura değişimlerini ve oylama güçlerini görmek için aşağıdaki kaydırıcıyı ayarlayın.',
    'landing.reputationIndex': 'İtibar Endeksi',
    'landing.activeAura': 'Aktif Aura Profili',
    'landing.unlockedBadges': 'Kazanılan Rozetler',
    'landing.featuresHeader': 'Kriptografik İtibarın Temel Direkleri',
    'landing.featuresDesc': 'Karma AI, küresel güven endeksini hesaplamak için akıllı sözleşme geçmişini, token tutma sürelerini ve yönetişim katılım oylarını analiz eder.',
    'landing.connectTitle': 'Güven Pasaportunuzu Oluşturun',
    'landing.connectDesc': 'Metrikleri sentezlemek, saklamasız yüksek itibar skorları elde etmek ve ayricalikli likidite rotalarına erişmek için cüzdanınızı bağlayın.',
    'dashboard.certificateTitle': 'İtibar Sertifikası',
    'dashboard.reputationCert': 'Doğrulanmış Egemen Kredi Kaydı',
    'dashboard.streak': 'Token Tutma Serisi',
    'dashboard.ranking': 'Küresel Kayıt Sırası',
    'dashboard.scoreBreakdown': 'İtibar Skoru Dağılımı',
    'dashboard.identityPillars': 'Davranışsal Kimlik Göstergeleri',
    'dashboard.liveAnalytics': 'Canlı Sandbox Analizleri',
    'dashboard.recentActivity': 'Son İşlem Günlüğü',
    'dashboard.activeState': 'Egemen Kimlik Düğümü Aktif',
    'lenders.title': 'Egemen Borç Verenler',
    'lenders.subtitle': 'Anında Teminatsız Kredi Ağ Geçidi',
    'lenders.desc': 'Teminatsız kredi tekliflerinden anında yararlanın. Yüksek itibar puanları, daha düşük faiz oranları (APR) ve devasa kredi limitleri sağlar.',
    'lenders.dynamicLimit': 'Kredi Limiti',
    'lenders.scoreBarrier': 'Gerekli Skor Barajı',
    'lenders.apr': 'Temsili Yıllık Faiz Oranı (APR)',
    'lenders.approvalRate': 'Kredi Onay Güveni',
    'lenders.requestQuote': 'Likidite Sözleşmesini İmzala',
    'leaderboard.title': 'Küresel Cüzdan Arenası',
    'leaderboard.subtitle': 'İtibarSkor Tablosu',
    'leaderboard.desc': 'Gerçek zamanlı güncellenen sıralamalar. Token tutma geçmişlerini, yönetişim serilerini ve seçkin cüzdanları hemen doğrulayın.',
    'leaderboard.score': 'Puan',
    'leaderboard.streakBadge': 'Seri',
    'leaderboard.search': 'Kayıt içinde cüzdan adresi ara...',
    'ai.title': 'Yapay Zeka Karma Kahini',
    'ai.subtitle': 'Yapay Zeka Aura Kalibrasyonu Yapılıyor...',
    'ai.desc': 'Yapay zeka kahinimiz, geçmiş işlemlerinizi, adres yaşınızı ve akıllı sözleşme etkileşimlerinizi analiz ederek özel ve kapsamlı bir itibar raporu hazırlar.',
    'ai.requestAudit': 'Derinlemesine Yapay Zeka Denetimi Talep Et',
    'ai.analyzing': 'On-chain işlemler taranıyor...',
    'footer.brand': 'Web3 itibarı için Kredi Karması. Makine öğrenimi, tahmin algoritmaları ve sıfır bilgi kanatlarını yenilikçi bir yapıda birleştirir.',
    'footer.infrastructure': 'Altyapı',
    'footer.ecosystem': 'Ekosistem',
    'footer.socialVectors': 'Sosyal Medya'
  },
  VI: {
    'nav.home': 'Trang chủ',
    'nav.dashboard': 'Karma của tôi',
    'nav.lenders': 'Khoản vay chủ quyền',
    'nav.leaderboard': 'Bảng xếp hạng',
    'nav.aiReading': 'Chẩn đoán AI',
    'nav.connect': 'Kết nối ví',
    'nav.disconnect': 'Ngắt kết nối',
    'nav.edit': 'Chỉnh sửa hồ sơ',
    'nav.comingSoon': 'Sắp ra mắt',
    'hero.badge': '🔒 Điểm uy tín tín dụng cho cộng đồng Web3 · Chế độ Sandbox hoạt động',
    'hero.titleLine1': 'Điểm Uy Tín',
    'hero.titleLine2': 'Và Danh Tiếng Crypto',
    'hero.subtitle': 'Tương tự điểm tín dụng, nhưng dành riêng cho Web3.',
    'hero.desc': 'Blockchain ghi lại số dư và giao dịch công khai, Karma AI đánh giá độ tin cậy được xác thực. Đo lường hoạt động, uy tín và mức cam kết giữ token. Tạo hộ chiếu uy tín nhanh chóng.',
    'solana.comingSoon': 'Token sắp ra mắt trên mạng Solana',
    'solana.utility': 'Token tiện ích $KARMA',
    'solana.launch': 'RA MẮT TRÊN SOLANA',
    'solana.powering': 'Hỗ trợ kiểm tra tín dụng DeFi bảo mật không tiết lộ thông tin, nâng cấp uy tín tức thì và phần thưởng xác định chéo chuỗi. Giữ $KARMA để nhận các hệ số nhân điểm.',
    'landing.sliderHeader': 'Bộ giả lập tính điểm uy tín',
    'landing.sliderDesc': 'Điều chỉnh thanh trượt để xem hạn mức tín dụng, thay đổi hào quang trực quan và hệ số quyền lực bỏ phiếu.',
    'landing.reputationIndex': 'Chỉ số uy tín',
    'landing.activeAura': 'Cấu hình hào quang',
    'landing.unlockedBadges': 'Huy hiệu đã đạt',
    'landing.featuresHeader': 'Trụ cột của Uy tín Mật mã học',
    'landing.featuresDesc': 'Karma AI phân tích lịch sử hợp đồng thông minh, chu kỳ giữ token và hoạt động quản trị để tính toán chỉ số uy tín toàn cầu.',
    'landing.connectTitle': 'Thiết lập Hộ chiếu uy tín',
    'landing.connectDesc': 'Kết nối ví phi tập trung an toàn để tổng hợp số liệu, nhận xếp hạng uy tín không lưu ký và mở khóa các định tuyến thanh khoản VIP.',
    'dashboard.certificateTitle': 'Chứng nhận danh tiếng',
    'dashboard.reputationCert': 'Hồ sơ tín dụng chủ quyền được xác thực',
    'dashboard.streak': 'Chu kỳ nắm giữ token liên tục',
    'dashboard.ranking': 'Xếp hạng danh bạ toàn cầu',
    'dashboard.scoreBreakdown': 'Chi tiết phân tích điểm uy tín',
    'dashboard.identityPillars': 'Nhân tố danh tính hành vi',
    'dashboard.liveAnalytics': 'Phân tích Sandbox trực tiếp',
    'dashboard.recentActivity': 'Nhật ký giao dịch gần đây',
    'dashboard.activeState': 'Nút nhận diện hoạt động',
    'lenders.title': 'Khoản vay chủ quyền',
    'lenders.subtitle': 'Cổng kết nối thanh khoản tức thì',
    'lenders.desc': 'Nhận đề xuất vay không cần thế chấp một cách nhanh chóng. Điểm uy tín càng cao giúp giảm lãi suất (APR) cạnh tranh và tăng hạn mức vay lớn.',
    'lenders.dynamicLimit': 'Hạn mức cho vay',
    'lenders.scoreBarrier': 'Điểm tối thiểu yêu cầu',
    'lenders.apr': 'Lãi suất hàng năm (APR)',
    'lenders.approvalRate': 'Độ tin cậy được duyệt vay',
    'lenders.requestQuote': 'Ký kết thỏa thuận thanh khoản',
    'leaderboard.title': 'Đấu trường ví toàn cầu',
    'leaderboard.subtitle': 'Bảng xếp hạng uy tín Web3',
    'leaderboard.desc': 'Bảng xếp hạng cập nhật thời gian thực. Xác nhận lịch sử hold token, chuỗi tham gia quản trị và các ví thuộc nhóm tinh anh.',
    'leaderboard.score': 'Điểm số',
    'leaderboard.streakBadge': 'Chuỗi',
    'leaderboard.search': 'Tìm kiếm ví trong danh bạ...',
    'ai.title': 'Bói toán Uy tín AI',
    'ai.subtitle': 'Đang hiệu chỉnh tâm lý hào quang AI...',
    'ai.desc': 'Hệ thống AI phân tích sâu lịch sử giao dịch, tuổi thọ ví và các tương tác hợp đồng thông minh để viết bản báo cáo đánh giá danh tiếng cá nhân hoàn hảo.',
    'ai.requestAudit': 'Yêu cầu kiểm toán AI chi tiết',
    'ai.analyzing': 'Đang quét giao dịch on-chain...',
    'footer.brand': 'Hệ thống đánh giá uy tín Web3 Karma. Kết hợp học máy máy tính, thuật toán dự đoán FICO và giải pháp bảo mật mật mã tiên tiến.',
    'footer.infrastructure': 'Cơ sở hạ tầng',
    'footer.ecosystem': 'Hệ sinh thái',
    'footer.socialVectors': 'Kênh xã hội'
  },
  KO: {
    'nav.home': '홈',
    'nav.dashboard': '마이 카르마',
    'nav.lenders': '주권 대출 기관',
    'nav.leaderboard': '글로벌 순위',
    'nav.aiReading': 'AI 신용평가',
    'nav.connect': '지갑 연결',
    'nav.disconnect': '연결 해제',
    'nav.edit': '프로필 편집',
    'nav.comingSoon': '출시 예정',
    'hero.badge': '🔒 크립토 평판을 위한 온체인 신용 평가 · 샌드박스 모드 활성화됨',
    'hero.titleLine1': '당신의 크립토',
    'hero.titleLine2': '평판 및 신용 점수',
    'hero.subtitle': '웹3 세상을 위한 신용 평점 시스템.',
    'hero.desc': '블록체인은 잔고와 거래 기록만을 저장하지만, Karma AI는 검증된 신뢰 행동을 분석합니다. 웹3 신뢰성, 거버넌스 참여도, 토큰 보유 홀딩력을 측정하여 나만의 온체인 신용 패스포트 신속 발급.',
    'solana.comingSoon': '솔라나 체인 토큰 출시 임박',
    'solana.utility': '$KARMA 유틸리티 토큰',
    'solana.launch': '솔라나 론칭',
    'solana.powering': '영지식 보증 DeFi 신용 평가, 평판 지수 즉시 상승, 교차 체인 검증자 혜택 시스템 지원. $KARMA 보유시 높은 가점 멀티플라이어 획득.',
    'landing.sliderHeader': '인터랙티브 평판 계산기',
    'landing.sliderDesc': '슬라이더 점수를 조절해 보며 신용 한도, 시각적 아우라의 변화, 거버넌스 투표권 가중치를 실시간으로 시뮬레이션해 보세요.',
    'landing.reputationIndex': '평판 지수',
    'landing.activeAura': '활성 아우라 프로필',
    'landing.unlockedBadges': '잠금 해제된 배지',
    'landing.featuresHeader': '크립토 평판의 주요 6대 핵심 차원',
    'landing.featuresDesc': 'Karma AI 알고리즘은 사용자의 스마트 계약 트랜잭션, 오랜 투자의 흔적 및 영구적 거버넌스 상태를 추적하여 글로벌 신뢰 점수를 도출합니다.',
    'landing.connectTitle': '신뢰 인증 패스포트 주조',
    'landing.connectDesc': '탈중앙화 지갑을 안전하게 연동하고 실시간 온체인 데이터를 분석하여 비수탁 평판 레이팅 점수와 특수 우대 유동성을 누려보세요.',
    'dashboard.certificateTitle': '평판 증명서',
    'dashboard.reputationCert': '검증된 주권 크립토 신용 기록',
    'dashboard.streak': '토큰 홀딩 연속 일수',
    'dashboard.ranking': '글로벌 레지스트리 순위',
    'dashboard.scoreBreakdown': '신용 평판 세부 분석',
    'dashboard.identityPillars': '행동 정체성 핵심 지표',
    'dashboard.liveAnalytics': '실시간 온체인 분석 샌드박스',
    'dashboard.recentActivity': '최근 온체인 트랜잭션 내역',
    'dashboard.activeState': 'Egemen 주권 노드 아이덴티티 활성됨',
    'lenders.title': '주권 대출 기관',
    'lenders.subtitle': '즉시 대출 매칭 라우터',
    'lenders.desc': '담보 없이 무담보 신용 대출을 즉시 평가해 보세요. 평판 점수가 우수할수록 더욱 합리적인 저금리 우대 이율(APR) 및 통큰 대출 한도가 승인됩니다.',
    'lenders.dynamicLimit': '승인 대출 한도',
    'lenders.scoreBarrier': '승인 기준 평판 점수',
    'lenders.apr': '기준 참고 이자율 (APR)',
    'lenders.approvalRate': '대출 심사 신뢰성',
    'lenders.requestQuote': '계약서 서명 및 실행',
    'leaderboard.title': '글로벌 월렛 아레나',
    'leaderboard.subtitle': '온체인 평판 순위표',
    'leaderboard.desc': '주요 자산의 실시간 온체인 평판 랭킹 서비스. 홀딩 일수, DAO 거버넌스 참여 수치 및 상위 랭커들의 투명한 상태 검증 가능.',
    'leaderboard.score': '점수',
    'leaderboard.streakBadge': '연속성',
    'leaderboard.search': '주소로 월렛 랭킹 조회...',
    'ai.title': 'AI 카르마 신탁',
    'ai.subtitle': '신경망 아우라 평판 보정 진행 중...',
    'ai.desc': '우리의 AI 평판 분석 모델을 통해 사용자의 트랜잭션 내역, 지갑 생성 주기, 연동된 프로토콜 기록을 다각도로 정밀 검사하여 개개인 맞춤 신용 에세이 리포트를 생성합니다.',
    'ai.requestAudit': 'AI 심층 신용 평가 시작하기',
    'ai.analyzing': '온체인 거래 흔적 스캔 진행 중...',
    'footer.brand': '웹3 크립토 평판을 선도하는 신용 점수 분석 시스템 Karma. 최첨단 머신러닝 분석 엔진, FICO 예측 모델 및 혁신적인 암호화 영지식 안착 기술의 융합.',
    'footer.infrastructure': '인프라스트럭처',
    'footer.ecosystem': '생태계',
    'footer.socialVectors': '소셜 채널'
  }
};

interface LanguageContextProps {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  supportedLanguages: Language[];
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>('EN');

  // Load language from localStorage
  useEffect(() => {
    try {
      const stored = localStorage.getItem('karma_language');
      if (stored && ['EN', 'ES', 'ZH', 'JA', 'DE', 'FR', 'RU', 'PT', 'TR', 'VI', 'KO'].includes(stored)) {
        setLanguageState(stored as LanguageCode);
      }
    } catch (err) {
      console.warn('LocalStorage not accessible for language cache:', err);
    }
  }, []);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('karma_language', lang);
    } catch (err) {
      console.warn('Could not cache language code:', err);
    }
  };

  // Translation lookup helper function
  const t = (key: string): string => {
    const activeDict = TRANSLATIONS[language] || TRANSLATIONS.EN;
    return activeDict[key] || TRANSLATIONS.EN[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, supportedLanguages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
